<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>yabushan</artifactId>
        <groupId>com.yabushan</groupId>
        <version>3.1.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>yabushan-form</artifactId>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>

    <dependencies>

        <!--velocity代码生成使用模板 -->
        <dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity</artifactId>
        </dependency>

        <!-- 通用工具-->
        <dependency>
            <groupId>com.yabushan</groupId>
            <artifactId>yabushan-common</artifactId>
        </dependency>

        <!-- 工作流模块-->
        <dependency>
            <groupId>com.yabushan</groupId>
            <artifactId>yabushan-activiti</artifactId>
            <version>3.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.yabushan</groupId>
            <artifactId>yabushan-poi</artifactId>
            <version>3.1.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.yabushan</groupId>
            <artifactId>yabushan-ai</artifactId>
            <version>3.1.0</version>
            <scope>compile</scope>
        </dependency>

    </dependencies>

</project>
