#???????
#oracle
database.driver.oracle = oracle.jdbc.OracleDriver

#Oracle8/8i/9i????thin???
database.driver.oracle.thin = oracle.jdbc.driver.OracleDriver

#mysql
database.driver.mysql = com.mysql.cj.jdbc.Driver

#mysql8
database.dirver.mysql8=com.mysql.cj.jdbc.Driver
#DB2???
database.driver.db2 = com.ibm.db2.jdbc.app.DB2Driver

#sqlserver
database.driver.sqlserver = com.microsoft.jdbc.sqlserver.SQLServerDriver

#Sybase
database.driver.Sybase=com.sybase.jdbc.SybDriver

#informix
database.driver.informix = com.informix.jdbc.IfxDriver




